name: 'Install flake8 for Ubuntu'
description: 'Install flake8 on Ubuntu for Python Validate'

runs:
  using: "composite"
  steps:
    - id: install-flake8 # run the run.py to get the latest data
      run: | 
        python -m pip install --upgrade pip
        python -m pip install flake8
      shell: bash