name: Nexus Download
description: This action downloads an artifact from nexus

inputs:
  serverUrl:
    description: Nexus URL
    required: false
    default: http://nexus.viavarejo.com.br
  repositoryName:
    description: Name of the nexus repository
    required: true
  projectName:
    description: Name of the project
    required: true
  artifactName:
    description: Name of the nexus artifact
    required: true
  outputDirPath:
    description: Output directory where the artifact will be downloaded
    required: false
    default: ./

runs:
  using: composite
  steps: 
    - name: Download
      run: |
        wget \
          ${{inputs.serverUrl}}/repository/${{inputs.repositoryName}}/${{inputs.projectName}}/${{inputs.artifactName}} \
          -P ${{inputs.outputDirPath}}
      shell: bash

    - name: Unzip artifact
      run: |
        unzip -o -d ${{inputs.outputDirPath}} ${{inputs.outputDirPath}}/${{inputs.artifactName}}
        rm ${{inputs.outputDirPath}}/${{inputs.artifactName}}
      shell: bash
