name: 'Getting a token for accessing the resouce'
description: 'Get Azure Access Token for an specific resource'
inputs:
  resource-url:
    description: 'Resource url for that you are requesting token'
    required: true
  resource-type-name:
    description: 'Optional resouce type name, supported values: AadGraph, AnalysisServices, Arm, Attestation, Batch, DataLake, KeyVault, OperationalInsights, ResourceManager, Storage, Synapse. Default value is Arm if not specified.'
    default: 'Arm'
outputs:
  token:
    description: "Authentication Token"
    value: ${{ steps.adquire-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - id: adquire-token
      name: Adquiring access token
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name Az.Accounts -AllowClobber -Force
        $context = Get-AzContext
        $resourceToken = (Get-AzAccessToken -ResourceUrl '${{ inputs.resource-url }}' -DefaultProfile $context).Token
        
        write-host "::debug::Set the token variable to value $resourceToken"
        write-host "::set-output name=token::$resourceToken"