name: 'Install databricks-cli for Ubuntu'
description: 'Install databricks-cli'

runs:
  using: "composite"
  steps:
    - id: install-databricks-cli # run the run.py to get the latest data
      run: | 
        python -m pip install --upgrade pip
        python -m pip install databricks-cli
      shell: bash