name: Databricks/Scala/CI

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - develop
    paths:
      - 'databricks/**.scala'

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: ./databricks

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

    # Action created by the devsquad
      - name: scalastyle-download
        uses: microsoft/scalastyle-download@v1.0.0

    # Action created by the devsquad
      - name: scalastyle-validate
        uses: microsoft/scalastyle-validate@v1.0.0
        with:
          scala-code-directory: './databricks'
          scalastye-config-directory: './databricks/config/scalastyle_config.xml'
