name: DataFactory/CD

on:
  workflow_dispatch:
  push:
    branches:
    - develop
    paths:
    - 'datafactory/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Export ARM Template
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: ./datafactory

    - name: Publish ARM template
      uses: actions/upload-artifact@v2
      with:
        name: adf-arm-template-dev
        path: ${{ steps.export.outputs.arm-template-directory }}
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Install Azure CLI
      uses: ./.github/actions/azcli-install
      
    - name: Install PowerShell
      uses: ./.github/actions/powershell-install

    - name: "Install Azure Powershell"
      uses: ./.github/actions/azure-powershell-install

    - name: "Azure login"
      uses: ./.github/actions/azure-login
      with:
        clientId: ${{ secrets.AZ_CLIENT_ID }}
        clientSecret: ${{ secrets.AZ_CLIENT_SECRET }}
        tenantId: ${{ secrets.AZ_TENANT_ID }}
    
    - name: "PowerShell login"
      uses: ./.github/actions/azure-login-powershell
      with:
        clientId: ${{ secrets.AZ_CLIENT_ID }}
        clientSecret: ${{ secrets.AZ_CLIENT_SECRET }}
        tenantId: ${{ secrets.AZ_TENANT_ID }}

    - name: Download ARM template
      uses: actions/download-artifact@v2
      with:
        name: adf-arm-template-dev
        
    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.0.1
      with:
        resourceGroupName: ${{ env.dataFactoryResourceGroup }}
        dataFactoryName:  ${{ env.dataFactoryName }}
        armTemplateFile: myArmTemplate.json
        additionalParameters: 'keyvault_url=${{ env.tribeKeyVaultUrl }} datalake_url=${{ env.sharedDataLakeUrl }}'
